version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
    time: "03:00"
  open-pull-requests-limit: 10
  reviewers:
  - valfirst
  ignore:
  - dependency-name: org.mockito:mockito-core
    versions:
    - 3.8.0
